config/routes.rb
 Bandblitz::Application.routes.draw do
  resources :sales
  resources :books
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/users', to: 'users#index'
  match '/mycontact', to: 'users#contact'

  root :to => 'static_pages#home'

  match '/home', :to => 'static_pages#home'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
  match '/help', :to => 'static_pages#help'

  match '/addbook', :to => 'books#new'
  match '/editbook', :to => 'books#edit'
  match '/view', :to => 'books#show'
  match '/books', :to => 'books#index'

  match '/newpost', :to => 'sales#new'
  match '/post', :to => 'sales#show'
  match '/editpost', :to => 'sales#edit'
  match '/sales', :to => 'sales#index'
  match '/checkout', :to => 'sales#checkout'

  match '/sales/:id/purchase' => 'sales#purchase', as: :purchase
  match '/add' => 'books#add', as: :add

end

app/views/partials/_footer.html.erb
<!--<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>-->

app/views/partials/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <!--<%= link_to "Bonfire", root_path, id: "logo" %> <nav>
        <img src="" alt="Bonfire">-->
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li> 
        <% if signed_in? %>
              <li><%= link_to "Sell Book", newpost_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>

                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Logout", logout_path, method: "delete" %>
                  </li> 
                  </li>    
                </ul>
            <% else %>
              <li><%= link_to "Register", signup_path %></li>
              <li><%= link_to "Login", login_path %></li>
            <% end %>

          </ul> </nav>
     <div id="rights" class="rights">
        Copyright © 2014 - 2014 Bonfire · All Rights Reserved | <u>Terms & Conditions</u>
      </div>
        </div>
      </div>
      
</header>

app/views/partials/_shim.html.erb
 <!--[if lt IE 9]>
 <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->