config/routes.rb
 Bandblitz::Application.routes.draw do
  resources :sales
  resources :books
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/users', to: 'users#index'
  match '/mycontact', to: 'users#contact'

  root :to => 'static_pages#home'

  match '/home', :to => 'static_pages#home'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
  match '/help', :to => 'static_pages#help'

  match '/addbook', :to => 'books#new'
  match '/editbook', :to => 'books#edit'
  match '/view', :to => 'books#show'
  match '/books', :to => 'books#index'

  match '/newpost', :to => 'sales#new'
  match '/post', :to => 'sales#show'
  match '/editpost', :to => 'sales#edit'
  match '/sales', :to => 'sales#index'
  match '/checkout', :to => 'sales#checkout'

  match '/sales/:id/purchase' => 'sales#purchase', as: :purchase
  match '/add' => 'books#add', as: :add

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :description, :edition, :isbn, :name, :photo, :retail_price
  has_and_belongs_to_many :sales

  validates(:isbn, presence: true, :uniqueness => true)
  validates(:name, presence: true)
  validates(:retail_price, presence: true)
  validates(:description, presence: true)
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  helper_method :add
  # GET /books
  # GET /books.json
  def add(num)
    #item = '9781133049791'
    item = num.fetch("isbn")
    if !Book.pluck(:isbn).include?(item)
      @res  = Amazon::Ecs.item_search(item,  { :search_index => 'All', :response_group => 'Medium' })
      @res.items.each do |book|
        @db = Book.create
        @db.isbn = item
        @db.author = book.get('ItemAttributes/Author')
        @db.name = book.get('ItemAttributes/Title')
        @db.edition = book.get('ItemAttributes/Edition').to_i
        @db.retail_price = ((book.get('ItemAttributes/ListPrice/Amount').to_f/100)*3.65).to_i
        @db.description = book.get('EditorialReviews/EditorialReview/Content')
        @db.photo = book.get('LargeImage/URL')
        @db.save
      end
    end
    @thisBook = Book.find(:all, :conditions => {:isbn => item})
    redirect_to @thisBook
  end

  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = params[:book]
    add(@book)
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
	def current_book
      @current_book ||= current_sale.books.all
  	end

  def current_book(sale)
      @current_book ||= sale.books.all
    end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.number_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :edition %><br />
    <%= f.number_field :edition %>
  </div>
  <div class="field">
    <%= f.label :retail_price %><br />
    <%= f.number_field :retail_price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% provide(:title, 'Edit Book') %>

<div class="hero-unit-white">


<h1>Edit Book</h1>


<%= form_for(@book, :html => { :multipart => true }) do |f| %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>

      <%= f.label :isbn, "ISBN" %>
      <%= f.text_field :isbn %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :author %>
      <%= f.text_field :author %>

      <%= f.label :edition %>
      <%= f.text_field :edition %>

      <%= f.label :retail_price, "Retail Price" %>
      <%= f.text_field :retail_price %>

      <%= f.label :description%>
      <%= f.text_field :description %>

      <%= f.label :photo, "Image URL"%>
      <%= f.text_field :photo %>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>

</div>

app/views/books/index.html.erb
<% provide(:title, 'All Books') %> 

<div class="hero-unit-white">


<h1>Listing Books</h1>


<ul class="books">
    <% @books.each do |book| %>
        <li>
            <td><%= link_to book.name, book %> <% link_to book %></td>
            	| <%= link_to "edit", edit_book_path(book) %>
          		| <%= link_to "delete", book, method: :delete, confirm: "You sure?" %>
        </li>
    <% end %> 
</ul>

<br></br>
<%= link_to "Add a Book", addbook_path, class: "btn btn-large btn-primary" %>



<% res = Amazon::Ecs.item_search('9780470128701',  { :search_index => 'All', :response_group => 'Medium' })%>
<% res.items%>
</div>

app/views/books/new.html.erb
<% provide(:title, 'New Book') %>

<div class="hero-unit-white">

<h1>New Book</h1>

<%= form_for(@book, :html => { :multipart => true }) do |f| %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>

      <%= f.label :isbn, "ISBN" %>
      <%= f.text_field :isbn %>
      <br></br>
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>
 </div>

app/views/books/show.html.erb
<% provide(:title, @book.name) %>

<div class="hero-unit-white">


<h4><%= @book.name %></h4>

<p><%= @book.description %></p>

<br></br>

<img src=<%=@book.photo%> alt=<%=@book.name%>>

<br></br>

<p>
  <b>ISBN:</b>
  <%= @book.isbn %>
</p>
<p>
  <b>Author:</b>
  <%= @book.author %>
</p>
<p>
  <b>Edition:</b>
  <%= @book.edition %>
</p>
<p>
  <b>Retail Price:</b>
  QR <%= @book.retail_price %>
</p>

<br></br>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

</div>