config/routes.rb
 Bandblitz::Application.routes.draw do
  resources :sales
  resources :books
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/users', to: 'users#index'
  match '/mycontact', to: 'users#contact'

  root :to => 'static_pages#home'

  match '/home', :to => 'static_pages#home'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
  match '/help', :to => 'static_pages#help'

  match '/addbook', :to => 'books#new'
  match '/editbook', :to => 'books#edit'
  match '/view', :to => 'books#show'
  match '/books', :to => 'books#index'

  match '/newpost', :to => 'sales#new'
  match '/post', :to => 'sales#show'
  match '/editpost', :to => 'sales#edit'
  match '/sales', :to => 'sales#index'
  match '/checkout', :to => 'sales#checkout'

  match '/sales/:id/purchase' => 'sales#purchase', as: :purchase
  match '/add' => 'books#add', as: :add

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :condition, :photo, :price, :book_id, :charity
  has_and_belongs_to_many :books
  has_and_belongs_to_many :users

  validates(:condition, presence: true)
  validates(:price, presence: true)
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  helper_method :purchase, :redirect
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new
  end
  
  def checkout
  end
  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    x = add(params[:sale])
    @sale = current_user.sales.new(x)
      if @sale.save
        @sale.users << current_user
        @sale.books << Book.find(@sale.book_id)
        @sale.owner_id = current_user.id
        @sale.save
        flash[:success] = "Post created!"
        redirect_to @sale
      else
        render 'new'
      end
    
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def purchase
    @sale = Sale.find(params[:id])
    if @sale.charity!= ""
      redirect_to checkout_path
    else
      if @sale.user_id == nil
        @sale.user_id = current_user.id
        @sale.save
        flash[:success] = "Please find the contact details below to purchase this product!"
        redirect_to User.find(@sale.owner_id)
      else
        redirect_to root_path
      end
    end
  end

  def redirect
    redirect_to root_path
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    current_user.sales.find(params[:id]).destroy
    flash[:success] = "Post destroyed"
    redirect_to users_path
  end
end

app/helpers/sales_helper.rb
module SalesHelper
	def admin?
    current_user.admin?
  end

  	def current_sale
    	@current_sale ||= current_user.sales.all
  	end

    def current_sale(user)
      @current_sale ||= user.sales.all
    end

    def current_book
      @current_book ||= current_sale.books.all
  	end

  def current_book(sale)
      @current_book ||= sale.books.all
  end

  def current_user
      @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user_id
      return User.find_by_remember_token(cookies[:remember_token]).id
  end
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :condition %><br />
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/checkout.html.erb
<% provide(:title, 'Purchase') %>
<div class="hero-unit-white">

  <h1>Purchase</h1>
  <h3> Page is placeholder for PayPal payments </h3>
</div>

app/views/sales/edit.html.erb
<div class="hero-unit-white">


<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

</div>

app/views/sales/index.html.erb
<% provide(:title, 'All Posts') %> 

<div class="hero-unit-white">

<h1>Listing Posts</h1>



<ul class="posts">
  <% @sales.each do |sale| %>
    <li>
      <td><%= link_to Book.find(sale.book_id).name, sale %> <% link_to sale %></td>
          | <%= link_to "edit", edit_sale_path(sale) %>
          | <%= link_to "delete", sale, method: :delete, confirm: "You sure?" %>
    </li>
  <% end %> 
</ul>

<br></br>
<%= link_to "Sell a Book", newpost_path, class: "btn btn-large btn-primary" %>

</div>

app/views/sales/new.html.erb
<% provide(:title, 'New Sale') %>

<div class="hero-unit-white">


<h1>New Sale</h1>

<%= form_for(@sale, :html => { :multipart => true }) do |f| %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@sale) do |f| %>

      <%= f.label :book_id, "ISBN (without dashes)" %>
      <%= f.text_field :book_id %>

      <%= f.label :price %>
      <%= f.text_field :price %>

      <%= f.label :condition%>
      <%= f.select :condition, ['New','Like New','Used'] %>

    <%= f.label :charity, "Charity*"%>
      <%= f.select :charity, [nil,'Qatar Red Crescent','QAWS', 'Reach Out To Asia (ROTA)', 'Qatar Charity'] %>
<br></br>

      <%= f.submit "Next", class: "btn btn-large btn-primary" %>
    <% end %>
    <br></br>
  <p>* Selecting a charity, once book is purchased all proceeds will go to the charity of your choice</p>
  </div>
  </div>
</div>
<% end %>


</div>

app/views/sales/show.html.erb
<% provide(:title, Book.find(@sale.book_id).name) %>


<div id="bookimage">
    <img src=<%=Book.find(@sale.book_id).photo%> alt=<%=Book.find(@sale.book_id).name%>>
</div>

<div id="details">
  <div id="booktitle">
    <h1><%= Book.find(@sale.book_id).name %></h1>
    <h2>
        <!--author-->
        <%= Book.find(@sale.book_id).author %>
    </h2>
  </div>



  <div id="saleinfo">
    <% if @sale.user_id == nil %>
      <h2>FOR SALE</h2>
    <% else %>
      <h3>Sold
    <% end %> Selling Price: QR <%= @sale.price %> ,
    Condition: <%= @sale.condition %></h3>

    <% if @sale.charity != nil && @sale.charity!="" %>
    <h3>Proceeds go to: <%= @sale.charity %></h3>
    <% end %>
  </div>

  <div id="bookdescription">
  <p><%= Book.find(@sale.book_id).description.html_safe %></p>
    <!-- @sale.owner_id.to_i != current_user.id.to_i && 
    -->
  </div>



  <!-- @sale.owner_id.to_i == current_user.id.to_i &&
   -->

    
    

    <div id="bookdata">
      <p>
        ISBN
        <%= Book.find(@sale.book_id).isbn %>
      </p>
      <p>
        Edition
        <% if Book.find(@sale.book_id).edition == 0 %>
        N/A
        <% else %>
        <%= Book.find(@sale.book_id).edition %>
        <% end %>
      </p>
      <p>
        Retail Price
        <% if Book.find(@sale.book_id).retail_price == 0 %>
        N/A
        <% else %>
        QR <%= Book.find(@sale.book_id).retail_price %>
        <% end %>
      </p>
      <br></br>
    </div>

  <div id="buttons"> 
    <% if signed_in? && @sale.user_id==nil %>
      <%= link_to 'Edit Sale', edit_sale_path(@sale), class: "btn btn-large btn-primary" %>
    <% end %>

    <br></br>
    
    <% if !signed_in? %>
      <%= link_to "Purchase", login_path, class: "btn btn-large btn-primary" %>
    <% elsif @sale.user_id == nil %>
      <%= link_to "Purchase", purchase_path, class: "btn btn-large btn-primary" %>
    <%end %>
  </div>
</div>